using System.Text.Json.Serialization;

namespace SAPB1.SLFramework.Enums
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    /// <summary>
    /// Represents the approval status of a document or transaction.
    /// Corresponds to SAP Business One approval statuses.
    /// </summary>
    public enum ApprovalStatusEnum
    {
        /// <summary>0 - Without a status.</summary>
        sasWithout = 0,

        /// <summary>1 - Pending: awaiting approval.</summary>
        sasPending = 1,

        /// <summary>2 - Approved but not yet converted from draft.</summary>
        sasApproved = 2,

        /// <summary>3 - Rejected: remains a draft.</summary>
        sasRejected = 3,

        /// <summary>4 - Generated: approved and converted by the originator.</summary>
        sasGenerated = 4,

        /// <summary>5 - Generated by authorizer: approved and converted by the authorizer.</summary>
        sasGeneratedbyAuthorizer = 5,

        /// <summary>6 - Cancelled: approval procedure cancelled; draft cannot be converted.</summary>
        sasCancelled = 6
    }
}
