name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack framework library
        run: |
          git_tag="${GITHUB_REF##*/}"       # e.g. v1.2.3
          version="${git_tag#v}"            # strip the leading ‘v’

          echo "📦 Packing version $version"

          dotnet pack SAPB1.SLFramework/SAPB1.SLFramework.csproj \
            --configuration Release \
            --output nupkg \
            --no-build \
            /p:Version="$version"

      - name: Push package to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push "nupkg/*.nupkg" \
            --api-key $NUGET_API_KEY \
            --source https://api.nuget.org/v3/index.json
